language: node_js
node_js: 6
os:
  - osx
  - linux
env:
  # Note: CCX vs. CXX? WTF FTW.
  # This is obviously not ideal. I never was good with linear algebra. Damn matrixes.
  - CCX=gcc-4.8 FULL_CHECK=false # osx
  - CCX=gcc-4.8 FULL_CHECK=true # osx
  - CXX=g++-4.8 FULL_CHECK=false # linux
  - CXX=g++-4.8 FULL_CHECK=true # linux
cache:
  directories:
    - "node_modules"
matrix:
  # Don't build for incompatible c compilers.
  exclude:
    - os: osx
      env: CXX=g++-4.8 FULL_CHECK=false
    - os: osx
      env: CXX=g++-4.8 FULL_CHECK=true
    - os: linux
      env: CCX=gcc-4.8 FULL_CHECK=false
    - os: linux
      env: CCX=gcc-4.8 FULL_CHECK=true
  allow_failures:
    - os: osx
      env: CXX=gcc-4.8 FULL_CHECK=true
    - os: linux
      env: CXX=g++-4.8 FULL_CHECK=true
# before_install:
before_script:
  # `npm install` is automatic
  - npm install node-gyp -g
  - npm install -g license-checker
  # Install cargo and cargo install emerald and move to project base.
  - bash ./dependencies.sh
script:
  # Generate current version information from git tags.
  # - git describe --tags --always > version.txt
  # - sed -E 's/v([[:digit:]]+\.[[:digit:]]+)\.[[:digit:]]-([[:digit:]]+)-g([a-f0-9]+)/v\1.\2+\3/' version.txt > version-app.txt
  # - sed -E 's/v([[:digit:]]+\.[[:digit:]]+)\.[[:digit:]]-([[:digit:]]+).+/v\1.\2/' version.txt > version-only.txt
  # - sed -E 's/v([[:digit:]]+\.[[:digit:]]+)\.[[:digit:]]-([[:digit:]]+).+/v\1.x/' version.txt > version-base.txt
  - if [[ $(license-checker --production --exclude '(GPL-2.0 OR MIT)' | grep GPL) ]]; then license-checker --production | grep -C 1 GPL && false; fi
  - npm run build
  - if [[ $FULL_CHECK == "true" ]]; then npm run lint --silent; fi
  # Don't sign the build for now.
  - env CSC_IDENTITY_AUTO_DISCOVERY=false npm run dist
  - ls -l ./dist/
  # Set up bintray deploy config.
  # - sed -E "s/APPVERSION/$(cat version-base.txt)/" bintray.tpl.json > bintray.json
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    # - gcc-multilib
    # - g++-multilib
    # - gcc-4.8-multilib
    # - g++-4.8-multilib
    # - ia32-libs
    # - libc6-dev #predefs
 deploy:
   provider: bintray
   file: "bintray.json"
   user: splix
   key:
     secure: "c50TvgsSeBMs8LoPO6nQVad3rie0Csh9l2KmwBCCZCLnJNA2nRTMM4EvlNiO8XiYKxms5h3KbzkZXCm+LCmsf+H8U0yupb44prg/MZ8HdvHQ4Qh/hEfQ8rESlxsgu6fjDjF779ge4gfYImyXHkBOCn/PoLkw+Akzw18l2dxsBnAecc+dHwBQ8NQ1Wh7CulD05DEG4SmdMuA/urj4f3kQGkb03jLF8/dNlf8HlTfgREaeKP9rpAtAKsoRIVC+34FdRWN/i8KG3TY+A3+M8bzIFCVNx+sXQ5YKbbtRQbuLPZPF/ELBWsMaxxHwlujhEbsBbZVkHGGZtKk8/EU1w9ZkEQWghXnkIuDxpqvSHzl491xhhpbf+7XL/uonAHlatoNDu3822vrp/eDj/Ys4vOF7F8dYQ7JIyhmXN/P3khehG7FG8mDBqXuImPtiltqvLBGMbsgUFIlaugaB45Zr/Oe2Umf97MgNJeSW/U5qLXN7sS4fPA/KAquty9yzFaxhgsY9iKiGJdAS6AC/CJxmhzEJWgwu6idAmN/L5BaRg29YTtaK+D6AwIVCky9hyHn0VhFN+ieF8H3P3fweG8PX4i63oqTs0+sAGGygzcN6xNit9NtJQ7i3QeGlzRIXfCh2cMz0pU5ErZrWy+kNH1ixzpW9VyugAl6qUQxnyIhbbY5ybIQ="
   on:
     branch: builder
   tags: true
