os: unstable
cache:
  - node_modules
environment:
  GCP_AUTH:
    secure: D377huvIQVDhaJmbw6gtWe3TcslpwSLY3NHnVyEVfNZxPa5wORMmindAKYjXKICBa2BvJVtm4gk3E8K3S1HcZeMFSTHbShEK5qiHwFov1ljhCx7pFCXnKTHlIRcwMkrvvPOugmiLNGI2BY1WLNNjNxmHqsW+yXrWiFsajkF7yB0aUDdZxEUIftQTgwiFaowRYrNVmBm24DVLcw2mx7pfe0L6vWyYxAkq664S6YKZCTzkhaJJM9l/Bx8ImY0nBGFlGNOczE+rRiVjfd5YXmvEg0bAyHEs8kTaEYr1hqTeG0LYHvwrf/6SAn5zLOIfGsqBub+YPKGoR96c5t3QKlZPR7ZMyE30KTRMy/JHpsfl9N2de9kejnx5hCL+QbrUIL+UcrJNhRL4IEJ27zauI7kngK+b1dxF7FJrL9jGd/qvUD0RDkxJ2hCOCwxwuyKj7Bx6Afmgawip/W2UbRsyXJuw6pEn53AWZI+5z0dUyC9zlSn8sAQVgXoQCj5VWW1SfUjp/o2tcilRkUIZT8EPVXIHvLJsQqjBElLd+XSAf0f1bBnQlAEuMUjlzBDkAISpCsNkPFaHmMpobEKzGEMaQWzl/kX69VFPvj5rAojSUqBlgCMdlvOfrPIe3ZNFK33J02Bhd1vOhCMM3IC2BJdpR4ROpNGT0RcmAZaWwdiblAR6+1K2AER6VDV9pOwSkL3CIYG+8AVa7Bj7+Pcm8I6UD+FsCd6pLBD8djP+N0i20928CMM2+iMYLMRJjhTlDRD7f86gKxOb6mkwBuU0mIjpT5oDspaueryKB1jh2LVt+448avRuOVbgxaEOEYtrKbynDOjCtBfRBOm7/VgvdjXxGIpXVm6A51rySdcInqZSRIEVzxxgcrliSZU/okXcBrIpeSM+iYF6Rl1Dpe144hV6Z9xx9JPFvqRddb/INB9xwvfQ1GZUzSH8JXtl6D5JCand7yfyJpmnMGEVz9Bw8Oinn5RZ3tjTkdETeRwyP1yYJ6X5CrKXED7oulFqCon9N6NQUkM8JA4NbGLWW7SaDLwb0mnOiCXXyeFgo7GnRgOeoVNfhZhuL2/8WVG66D8MSnnNQlDd6/qsOGZaq+b6R2mkse7/gaA+VMZpK4dF53kQSyyR5Lcybog/GvhSFouc09ZFN8PwdMWyRqg3zfqdCB6p4a+ABapeU/k4SrUtT1vPxLfIGRbdCh3uaEx2mL3T9+Ir0b9pTMUM6ZdCjsQ363cbP3zf8C0UgDfkYTCrW6O+zsnrre9jjJIhCG1VV0YZfiGIo0jknmzhvAWFo2Dbhb1Rsqf3To2Eu8ws7YoaqK6TXKxAoVBht06Mvzp6aEkRvoS30mYY9oHG4rJXiAjdyHEffQwF/FRZC+enJDO4PzP1j0+TQub1HeMIdb8VjnI+r4MJ6gK03+Fv/eqPcKdYFU4agMHjW75K3fHcaluq+S/P7GA4HWU23mMQyktpDycCSLZFQdlBxPu7JlzhGTv41OiGFaz8tX4/qEYVJMlMIjZfI2RJyPXN7g73IZ9MBknfyX561n6kDhBUPV2W9i64TrNGInNozIPK6v3xjaPXX/NVcG6Je0TTYEa8b9+6gPqIubvUoI57cwZOVzkol6O6ZhaYNSv1pORZUHQ266nWW+z88w6dXIghCYLhaAPKVcHosB0lrU9ro8gWMV7R82k7VqqfzIbwmVZsl4E0nc9gIQ1429z6qEijB0DFIHu006Qy9mzgVFnq26QoncBmHxRCk1Ui5aDvqfDGJZJGIVd2T0syBBRO+9KFSOAbpcHA1nQQBNLAgoQ2h1wRcz4LTNhq66llU7NUv/5zHqfvxu7U82BqFHlZ/EBDbXLFYR4yrGp+HbqNoTJ3bBHzzUQWyD1RL0ml6dMfbTaOtQRozWcgiHraZTMyI1G7JFWSTWnDpno/Q+xeEVJ4i5FpdapzbzXiHBhdhIrSev2G6SSot+lhwqCQp24dp3pbHTTTdgDEBTwk61m/pj8p/GxiMkSBUO2UOlv+3S1gf8B7Or694ACSBYZsgpVIcUvJy12oUNvc9rTTA+QvmeWwN+8OvOluQdzi7FDxOMJLLYUpYp4AN/5LNlArR1U8AwerYbLKtAQuHOBMlAG/SAIT3JdPZyhqwwhmF+onXlPlSsnWE24NNTuW0HmEh5TMF2VXg7fqj6fFA1pzVwyjgan2UQ0TPWPNVA8tXPWMOWlt79W/Suevgn+qDiWpq9sNLN7XBzTpNZg8gYebniT6KUmNTmXWLBzbCu0i4cOdN/Jpi+rbhWBiDFg4+F/nY2CAY9+arb/WEgtu6GMbuWa+ZLHeEUkGLSN6vy7bwsyn8aUsMbQGxI4Wq4/fzM7Hk4bykV4dOoiYTqhA0hTx6PqvFoIrPP4KE+EzQNs/2R0wbwOQNeqcDEU3RnYS5XpNhCjR7QMuyL59L5LV4dWKC4xL0lWKMcrBZYXU9wMVBwko8heQRmH9zVrZLlrhenBq1rhG0t93ZRttgif7AVrPHCRKP+yHIOhqryZIsZkQWZRdnLHggxiM0y8ZztUf6anTwNsMTOujwHSvlHsIpTxOviViJ0d2mIWOpbI5mTCuRC4etBApfBJreuYYF6a4wX39ANIO6eLBq3MgZCZF8aRNjGEeAPyh/db6ULVFEIEAwfNyn7AmKyB2RqyPHJGqIdib5RPESfAcA1INXqo7GnLjapP+WJllxzgpctCcc5Nu7GJKFD1QN3rLq96RzMCMzbRT/o8dmt1dwbkBbMAHSaTv81GoHCWYqRXkgIjxu91BBDCnJaNHRrn9qd/J+wcI9ptLpBxe7iyB/eNHxa7TipGv5mfWX2IJGeVZpuBH0a1iUnhjMzoNMGIV4jRBncCFiOEH+Y/E0Ji1DyTeFpV5l/RGr1kTKQVdYYgMYwfvFItcrrL8l7kjwYqF3h7gAGNF61JGi3yktOYtKdto8PL5x594epZDEQQJNNFuiHqP0tbWIO06E7PYWlNUllBzi0oveOalbfD23JowNTTJfiB+UAAyMsRGBqkxd4eCQLsnx8RLUBOovFpVnkE9Wk172YS0+scX4zuB6KurH5ztyIIQmLuqzuc3eJ+XQ1YrderBTSjxxGhxHJHwhSdWW5uA7IG95KQdPF5SUmdTkCsrwx7tq/YfdnVvT8qF1b0VwmuSfApKSsjFPup23sVfbYMUiEN/UJvc0BBrAhimqb+shy4vgY9Ib9hOxxprNENkjB0HkSKfRjhD6/tk9NMvgXl1zod2wV0/XBENXorg2CllPOu4x4+6edkwJBQj0NdVXCxTU0LLjASgCaTN0x3dpRIoiVau6RdioNFujzrYWbe8CzpLFaRmd96pq5AyTkNjLOa9aYEyt1f6lZFlAH4z9M0j/KW+gPXOB+uLNGOCSYVCmimco9GhIZTyizXxMPM+6hrGxVf6UwzIXtrGN1CgufGZ7iLQVY5SBaLm4E7vQ8iZWEux8nUYCLWvJSW/Wa5U4a2QN1dELvIY3LEpZmtGvRkXrYVYGuJZNQ231AFBywVoj80STVFQVWgqKDn+FCjqpWTr4GfaIOvT3BzhvJiuSkMS1noLomysPuHX0sE6dPFNINSJs6d7N1xbeyIfmedK8sBmLZPVtl/GbNmZjeqRdbp9WKw7o5yWYL32f8ME6WyK+Osz+StPpch6GFHtiT789Nl1kB3QVs1E1XdBp7a/WQ9Kp1FCmz1+y3biMn0orQTRc2ld0nemnsYucXJTzVU6qZfoJhjLHROrh+bP0BIXkd6NMVbGAmaOtrojtkx41WSKiGA4/VBkTNXF6jZGlCPFDP9a7BIS5qtPy0fqfusczukVxFnS4HlSmhAb4uhVWUY1WS2AE2VsZ6imHjJkkygCuvP/LEe9YlFX2vmD10AM2JWt7eggBLRNPOaXyBScod+yKJXwQQuEYeouawvhRN1ngAfkJmf92zL3e9/YNwVKAtHufh/ore6bRipQcpvKKiQxNG9gF53ApCM5MZf7SbIpT3Lr/W0Nba9kuhh3QQc7GKslDXR/1PYc3wDZCOnL/wbVQbltZPeuc5XC1vTSScy7c+HypLbHFTt0rprGFw0UiKWffLPEyat8gAtAFPpCt4JcXHXuOafW8YicGfzYe3d/15Np40kcb8rcrLKPNof3lo37l3eUcnrw27nWQRRSeZoqHwElpIVnNN3i0Uh1rYDTT9fUcufCCY9MR5zh4M0mpoEAoTafZCqVG95/1/DbpR8TCKRqvpkpvdi1+AIdl14dnxTIEQxK6hKPNIJxCmvmo8SX1eaI5YGiMW18d7oIFQdq88Ihazl9oECH4gd4
  matrix:
    - nodejs_version: 6
install:
  # Set up version from git tags.
  - git describe --tags --always > version.txt
  - sed -E 's/v([[:digit:]]+\.[[:digit:]]+)\.[[:digit:]]-([[:digit:]]+)-g([a-f0-9]+)/v\1.\2+\3/' version.txt > version-app.txt
  - sed -E 's/v([[:digit:]]+\.[[:digit:]]+)\.[[:digit:]]-([[:digit:]]+).+/v\1.\2/' version.txt > version-only.txt
  - sed -E 's/v([[:digit:]]+\.[[:digit:]]+)\.[[:digit:]]-([[:digit:]]+).+/v\1.x/' version.txt > version-base.txt
  - set /p VERSION=<version-app.txt
  - set /p APP_VERSION_GIT_TAG=<version-app.txt
  - set /p VERSION_ONLY=<version-only.txt
  - set /p VERSION_BASE=<version-base.txt
  - echo %VERSION_BASE% %VERSION_ONLY% %VERSION%
  # Set up build dependencies.
  - ps: Install-Product node $end:nodejs_version
  - set CI=true
  - npm install -g npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
  - bash ./dependencies.sh
build: off
version: '{build}'
test_script:
  # CSC...=false env var disables app signing for osx, can't hurt to have it here too.
  # But probably useless, since the dist script build for _current_ operating system.
  - npm run dist
# Taken from go-ethereum.
artifacts:
  - path: './dist/*.exe'
    name: emerald-wallet
before_deploy:
  # Set up GCP upload.
  - npm install gcloud-storage-upload
  - ps: >-
      $bytes = [System.Convert]::FromBase64String($env:GCP_AUTH)

      [System.IO.File]::WriteAllBytes("gcloud.json", $bytes)
      
  - dir
deploy_script:
  - ps: >-
      If ($env:APPVEYOR_REPO_BRANCH -eq 'builder') {
          node .\node_modules\gcloud-storage-upload\lib\index.js -c gcloud.json --path dist\EmeraldWallet-win-%APP_VERSION_GIT_TAG%.exe --remotePath emerald-wallet\preview\
      }
