os: unstable
cache:
  - node_modules
environment:
  GH_TOKEN:
    secure: 3UjvS391L93QntuiuqFxNys8h6fJnYEo3WO4ObuRWVme927ee7qlT55U0eaKN+x5
  matrix:
    - nodejs_version: 6
install:
  - ps: Install-Product node $end:nodejs_version
  - set CI=true
  - npm install -g npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
  # I don't even know if windows haz bash.
  - bash dependencies.sh
build: off
version: '{build}'
test_script:
  - env CSC_IDENTITY_AUTO_DISCOVERY=false npm run dist
